stages:
  - check
  - test
  - release
  - deploy

default:
  image: node:22-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_COMMIT_TAG =~ /^v/

include:
  - local: .gitlab/ci.yml
  - local: .gitlab/release.yml
  - local: .gitlab/deploy.yml
