services:
  bark-web:
    build:
      context: .
      dockerfile: docker/bark-web.Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
      - wallet-data:/wallet-data:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - barkd
      - bark-web-api
    entrypoint: ['/bin/sh', '/app/docker/bark-web-entrypoint.sh']

  bark-web-api:
    container_name: bark-web-api
    build:
      context: .
      dockerfile: docker/bark-web-api.Dockerfile
    ports:
      - '4001:4001'
    volumes:
      - wallet-data:/wallet-data:ro
    environment:
      - ALLOWED_ORIGINS=http://localhost:5173
      - PORT=4001
      - WALLET_DIR=/wallet-data/.bark
    depends_on:
      - barkd

  bark:
    container_name: bark
    build:
      context: .
      dockerfile: docker/bark.Dockerfile
      args:
        BARK_VERSION: ${BARK_VERSION:-0.1.4}
    volumes:
      - wallet-data:/root

  barkd:
    container_name: barkd
    build:
      context: .
      dockerfile: docker/barkd.Dockerfile
      args:
        BARK_VERSION: ${BARK_VERSION:-0.1.4}
    environment:
      - BARKD_ALLOWED_ORIGINS=http://localhost:5173
    ports:
      - '4000:4000'
    volumes:
      - wallet-data:/root

volumes:
  wallet-data:
