export interface Tag {
  name: string
  createdAt: string
}

export interface Contact {
  id: string
  name: string
  createdAt: string
}

export type AnnotationSource = 'binding' | 'manual'

export interface TransactionAnnotation {
  movementId: number
  label?: string
  tags: string[]
  contactId?: string
  source: AnnotationSource
  createdAt: string
}

export interface OnchainAnnotation {
  outpoint: string
  label?: string
  tags: string[]
  createdAt: string
}

export interface AnnotationInput {
  label?: string
  tags: string[]
  contactId?: string
}

export type BindingDirection = 'incoming' | 'outgoing'

/**
 * Pending link between user-supplied metadata (label/tags) and the destinations
 * (ark/onchain addresses, lightning invoices) generated by a send or receive
 * flow. When a movement matches one of the destinations, the metadata is
 * promoted into a TransactionAnnotation for that movement.
 */
export interface DestinationBinding {
  id: string
  direction: BindingDirection
  destinations: string[]
  label?: string
  tags: string[]
  contactId?: string
  createdAt: string
}
